name: Ruff

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3.2.1
        with:
          src: "./src"
          args: check --select E,F,I --fix